//funções de data e hora

SELECT ADD_MONTHS('Jul 01, 2013', 13)
FROM dual;

SELECT LAST_DAY('Jul 01, 2013')
FROM dual;

SELECT NEXT_DAY('Jul 03, 2013', 1)
FROM dual;

SELECT ROUND(TO_DATE('Jul 03, 2013'), 'YYYY')
FROM DUAL;

SELECT TO_CHAR
        (ROUND
        (TO_DATE('Jul 03, 2023 19:45:26', 'MONTH DD, YYYY HH24:MI:SS'),
                'HH24'),
                'MONTH DD, YYYY HH24:MI:SS')
FROM dual;

SELECT
EXTRACT(YEAR FROM TO_DATE('Jul 03, 2023 19:45:26',
'MONTH DD, YYYY HH24:MI:SS')) AS ANO,
EXTRACT(MONTH FROM TO_DATE('Jul 03, 2023 19:45:26',
'MONTH DD, YYYY HH24:MI:SS')) AS MES,
EXTRACT(DAY FROM TO_DATE('Jul 03, 2023 19:45:26',
'MONTH DD, YYYY HH24:MI:SS')) AS DIA
FROM dual;

--INTERVALO DE TEMPO 
SELECT * 
FROM tb_promocao;

SELECT *
FROM tb_promocao;

--FUNCOES DE INTERVALO DE TEMPO: NUMTODSINTERVAL- CONVERTE UM NUMERO EM UMA UNIDADE DE VALOR
SELECT 
   NUMTODSINTERVAL(1.5, 'DAY'),
   NUMTODSINTERVAL(3.25, 'HOUR'),
   NUMTODSINTERVAL(5, 'MINUTE'),
   NUMTODSINTERVAL(10.123456789, 'SECOND')
FROM dual;


SELECT 
   NUMTOYMINTERVAL(1.5, 'YEAR'),
   NUMTOYMINTERVAL(3.25, 'MONTH')
FROM dual;